# This workflow will install Python dependencies, run tests, lint, and build an exe with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install  -i https://mirrors.aliyun.com/pypi/simple/ -r requirements.txt
          pip install pyinstaller
      - name: Build exe with PyInstaller
        run: |
          pyinstaller -w -F --add-data "fetch_all_message.py:." --add-data "util:util" --add-data "resource:resource" main.py
      - name: 输出项目目录下文件树
        run: |
          tree -L 5
      - name: Create GitHub release
        uses: softprops/action-gh-release@master
        with:
          files: dist/main
          tag_name: v1.0.0
          release_name: "Initial release"
          body: "This is the initial release of my Python application."
