# This workflow will install Python dependencies, run tests, lint, and build an exe with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install  -i https://mirrors.aliyun.com/pypi/simple/ -r requirements.txt
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install pyinstaller
        run: |
          pip install pyinstaller
      # - name: Lint with flake8
      #   run: |
      #     # stop the build if there are Python syntax errors or undefined names
      #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
      #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      # - name: Test with pytest
      #   run: |
      #     pytest
      - name: Build exe with PyInstaller
        run: |
          pyinstaller --onefile main.py
      - name: Create GitHub release
        uses: softprops/action-gh-release@master
        with:
          files: dist/main.exe
          tag_name: v1.0.0
          release_name: "Initial release"
          body: "This is the initial release of my Python application."
